# Generated by Django 3.2.3 on 2021-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galapp', '0003_alter_photos_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
