# Generated by Django 3.2.3 on 2021-05-29 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galapp', '0005_alter_photos_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chosen', to='galapp.photos', verbose_name='избранные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chosen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
